<?php

const UNDEFINED_MATERIALS_GROUP_NAME = 'Сырье, не включенное в основной список';
const UNDEFINED_MATERIALS_GROUP_CODE1C = 'G00000000';

const UNDEFINED_MATERIALS_CATEGORY_NAME = 'Наименование материалов';
const UNDEFINED_MATERIALS_CATEGORY_CODE1C = 'C00000000';

